[package]
name = "chess-r"
version = "0.9.0"
edition = "2024"
authors = ["3500pts"]

[dependencies]
bitvec = "1.0.1"
ggez = "0.9.3"
rand = "0.9.1"
tokio = { version = "1.44.2", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.19", features = ["env-filter"]}
